# Generated by Django 3.0.4 on 2020-03-19 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('identifier', models.CharField(max_length=1, verbose_name='Pilihan')),
                ('label', models.CharField(max_length=500, verbose_name='Jawaban')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Skor')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('explanation', models.TextField(blank=True, verbose_name='Penjelasan Jawaban')),
                ('right_choice', models.BooleanField(default=False, verbose_name='Ini Jawaban Benar')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Pilihan',
                'verbose_name_plural': 'Pilihan',
                'db_table': 'tryout_choice',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255, verbose_name='Nama Paket')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dan Jam Mulai')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dan Jam Selesai')),
                ('duration', models.IntegerField(blank=True, help_text='Durasi dalam menit.', null=True, verbose_name='Durasi')),
                ('chance', models.IntegerField(help_text='Kesempatan mengulang. 0 untuk tidak ada pengulangan', verbose_name='Boleh Mengulang?')),
                ('passed_score', models.IntegerField(verbose_name='Minimal Skor Lolos')),
                ('classification', models.PositiveIntegerField(choices=[(1, 'Live'), (2, 'Skor')], verbose_name='Jenis')),
                ('education_level', models.PositiveIntegerField(blank=True, choices=[(1, 'Sekolah Dasar'), (2, 'Sekolah Menengah Pertama'), (3, 'Sekolah Menengah Atas'), (4, 'Perguruan Tinggi'), (5, 'Semua')], null=True, verbose_name='Jenjang')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Konsep'), (2, 'Ditinjau'), (3, 'Publik')], default=1, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paket',
                'db_table': 'tryout_packet',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numbering', models.IntegerField(editable=False, null=True)),
                ('label', models.CharField(max_length=500, verbose_name='Judul Pertanyaan')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Skor')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryout.Packet', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Pertanyaan',
                'verbose_name_plural': 'Pertanyaan',
                'db_table': 'tryout_question',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('true_score', models.IntegerField(null=True)),
                ('false_score', models.IntegerField(null=True)),
                ('none_score', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Durasi dalam menit.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Jika ini sub-materi, pilih materi utamanya.', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tryout.Theory')),
            ],
            options={
                'verbose_name': 'Materi',
                'verbose_name_plural': 'Materi',
                'db_table': 'tryout_theory',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('right_choice', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tryout.Choice')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryout.Packet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryout.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jawaban',
                'verbose_name_plural': 'Jawaban',
                'db_table': 'tryout_respond',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sub_theory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_theories', to='tryout.Theory', verbose_name='Sub Materi'),
        ),
        migrations.AddField(
            model_name='question',
            name='theory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theories', to='tryout.Theory', verbose_name='Materi'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryout.Question'),
        ),
        migrations.CreateModel(
            name='Acquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_half', models.IntegerField(blank=True, editable=False, null=True)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryout.Packet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paket Dikerjakan',
                'verbose_name_plural': 'Paket Dikerjakan',
                'db_table': 'tryout_acquired',
                'abstract': False,
                'unique_together': {('user', 'packet')},
            },
        ),
    ]
