# Generated by Django 3.0.4 on 2020-03-21 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tryout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('right_choice', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jawaban',
                'verbose_name_plural': 'Jawaban',
                'db_table': 'tryout_answer',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='acquired',
            options={'verbose_name': 'Paket Dibeli', 'verbose_name_plural': 'Paket Dibeli'},
        ),
        migrations.AddField(
            model_name='choice',
            name='packet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tryout.Packet', verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='acquired',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquireds', to='tryout.Packet'),
        ),
        migrations.AlterField(
            model_name='acquired',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquireds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tryout.Question'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='classification',
            field=models.CharField(choices=[('live', 'Live'), ('score', 'Skor')], default='score', max_length=255, verbose_name='Jenis'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='education_level',
            field=models.CharField(blank=True, choices=[('sd', 'Sekolah Dasar'), ('smp', 'Sekolah Menengah Pertama'), ('sma', 'Sekolah Menengah Atas'), ('college', 'Perguruan Tinggi'), ('all', 'Semua')], default='all', max_length=255, null=True, verbose_name='Jenjang'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='status',
            field=models.CharField(choices=[('draft', 'Konsep'), ('reviewed', 'Ditinjau'), ('published', 'Terbit')], default='draft', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tryout.Packet', verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_theory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tryout.Theory', verbose_name='Sub Materi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tryout.Theory', verbose_name='Materi'),
        ),
        migrations.DeleteModel(
            name='Respond',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tryout.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='packet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tryout.Packet'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tryout.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
