# Generated by Django 3.0.4 on 2020-03-22 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tryout', '0002_auto_20200321_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquired',
            name='duration_half',
        ),
        migrations.RemoveField(
            model_name='acquired',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='acquired',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='acquired',
            name='starting_date',
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_half', models.IntegerField(blank=True, editable=False, null=True)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('chance', models.IntegerField(default=1)),
                ('is_done', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('acquired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='tryout.Acquired')),
                ('packet', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='tryout.Packet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paket Dikerjakan',
                'verbose_name_plural': 'Paket Dikerjakan',
                'db_table': 'tryout_simulation',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tryout.Simulation'),
        ),
    ]
