# Generated by Django 3.0.4 on 2020-03-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0003_auto_20200322_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='starting_date',
            new_name='start_date',
        ),
    ]
