# Generated by Django 3.0.4 on 2020-03-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0004_auto_20200322_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('packet', 'question', 'choice', 'simulation')},
        ),
    ]
