# Generated by Django 3.0.4 on 2020-03-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0007_auto_20200322_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tryout.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
