# Generated by Django 3.0.4 on 2020-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0009_auto_20200322_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
