# Generated by Django 3.0.4 on 2020-03-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0010_auto_20200322_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_type',
            field=models.CharField(choices=[('general', 'Umum'), ('national', 'Nasional')], default='general', max_length=255, null=True),
        ),
    ]
