# Generated by Django 3.0.4 on 2020-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0012_auto_20200330_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='scoring_type',
            field=models.CharField(choices=[('true_false_none', 'Benar, Salah, Kosong'), ('preference', 'Menurut Pilihan')], default='true_false_none', max_length=255, null=True),
        ),
    ]
