# Generated by Django 3.0.4 on 2020-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0013_theory_scoring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numbering_local',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
