# Generated by Django 3.0.5 on 2020-04-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0015_auto_20200411_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Pembahasan'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Pembahasan'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.TextField(verbose_name='Jawaban'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='right_choice',
            field=models.BooleanField(default=False, verbose_name='Jawaban Benar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_theory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_sub_theory', to='tryout.Theory', verbose_name='Sub Materi'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='duration',
            field=models.IntegerField(help_text='Durasi dalam menit.', null=True),
        ),
    ]
