# Generated by Django 3.0.5 on 2020-04-17 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0016_auto_20200413_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Contoh: Try Out UTBK', max_length=255, verbose_name='Nama')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'db_table': 'tryout_category',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='packet',
            name='theories',
            field=models.ManyToManyField(related_name='packets', to='tryout.Theory', verbose_name='Materi'),
        ),
        migrations.AddField(
            model_name='packet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tryout.Category'),
        ),
    ]
