# Generated by Django 3.0.5 on 2020-04-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0017_auto_20200417_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='minimum_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
