# Generated by Django 3.0.5 on 2020-04-20 02:52

import apps.tryout.models.abstract
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tryout', '0018_theory_minimum_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquired',
            name='status',
            field=models.CharField(choices=[('hold', 'Menunggu'), ('active', 'Aktif')], default='hold', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.tryout.models.abstract.directory_image_path)),
                ('value_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.tryout.models.abstract.directory_file_path)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, max_length=500, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(app_label='tryout'), on_delete=django.db.models.deletion.CASCADE, related_name='tryout_entity_attachment', to='contenttypes.ContentType')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'tryout_attachment',
                'ordering': ['-date_updated'],
                'abstract': False,
            },
        ),
    ]
