# Generated by Django 3.0.5 on 2020-04-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tryout', '0019_auto_20200420_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='tryout'), on_delete=django.db.models.deletion.CASCADE, related_name='tryout_attachment', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
