# Generated by Django 3.0.6 on 2020-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0021_auto_20200423_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='coin_amount',
            field=models.BigIntegerField(blank=True, help_text='Harga dalam Koin. Ini akan berfungsi hanya untuk tindakan Re-buyRe-buy adalah tindakan membeli ulang paketsetelah limit Boleh Mengulang terlampaui.', null=True),
        ),
    ]
