# Generated by Django 3.0.5 on 2020-04-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mypoints', '0004_auto_20200330_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='caused_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'tryout'), ('model', 'simulation')), models.Q(('app_label', 'tryout'), ('model', 'affiliateacquired')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
