# Generated by Django 3.0.4 on 2020-03-30 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_voucher_voucheracquired'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherRedeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redeems', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redeems', to='market.Voucher')),
            ],
            options={
                'verbose_name': 'Voucher Redeem',
                'verbose_name_plural': 'Voucher Redeems',
                'db_table': 'market_voucher_redeem',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VoucherAcquired',
        ),
    ]
