# Generated by Django 3.0.4 on 2020-03-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200330_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dan Jam Selesai'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='simulation_type',
            field=models.CharField(choices=[('general', 'Umum'), ('national', 'Nasional')], default='general', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dan Jam Mulai'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='coin_amount',
            field=models.BigIntegerField(help_text='Jika gratis isi dengan nol.'),
        ),
    ]
