# Generated by Django 3.0.4 on 2020-03-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_auto_20200330_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePasswordPassed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_passwords', to='market.Bundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bundle Password Passed',
                'verbose_name_plural': 'Bundle Password Passeds',
                'db_table': 'market_bundle_passoword_passed',
                'abstract': False,
            },
        ),
    ]
