# Generated by Django 3.0.5 on 2020-04-07 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_affiliate_affiliateacquired_affiliatecommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('ipaddr', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Affiliate Capture',
                'verbose_name_plural': 'Affiliate Captures',
                'db_table': 'market_affiliate_capture',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='code',
            field=models.CharField(editable=False, max_length=255, verbose_name='Kode Referral'),
        ),
    ]
