# Generated by Django 3.0.5 on 2020-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200407_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar')], default='in', max_length=255),
        ),
    ]
