# Generated by Django 3.0.5 on 2020-04-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0009_auto_20200408_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Bought Proof',
                'verbose_name_plural': 'Bought Proofs',
                'db_table': 'market_bought_proof',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['-date_created'], 'verbose_name': 'Bundel', 'verbose_name_plural': 'Bundel'},
        ),
        migrations.AddField(
            model_name='bought',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('hold', 'Hold')], default='accept', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BoughtProofRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Bought Proof Requirement',
                'verbose_name_plural': 'Bought Proof Requirements',
                'db_table': 'market_bought_proof_requirement',
                'abstract': False,
                'unique_together': {('label',)},
            },
        ),
        migrations.CreateModel(
            name='BoughtProofDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_image', models.ImageField(blank=True, max_length=500, upload_to='images/proof')),
                ('value_file', models.FileField(blank=True, max_length=500, upload_to='files/proof')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('bought_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_proof_documents', to='market.BoughtProof')),
                ('bought_proof_requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_proofs', to='market.BoughtProofRequirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_proof_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bought Proof Document',
                'verbose_name_plural': 'Bought Proof Documents',
                'db_table': 'market_bought_proof_document',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boughtproof',
            name='bought',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bought_proof', to='market.Bought'),
        ),
        migrations.AddField(
            model_name='boughtproof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='boughtproof',
            unique_together={('bought',)},
        ),
    ]
