# Generated by Django 3.0.5 on 2020-04-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_boughtproofrequirement_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bought',
            options={'ordering': ['-date_created'], 'verbose_name': 'Dibeli', 'verbose_name_plural': 'Dibeli'},
        ),
        migrations.AlterField(
            model_name='boughtproofdocument',
            name='bought_proof_requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_proof_documents', to='market.BoughtProofRequirement'),
        ),
    ]
