# Generated by Django 3.0.5 on 2020-04-28 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link_to', models.CharField(blank=True, max_length=500)),
                ('link_target', models.CharField(blank=True, choices=[('self_window', 'Self'), ('new_window', 'New Window')], default='self_window', max_length=255)),
                ('image', models.ImageField(blank=True, max_length=500, upload_to='images/banner')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'cms_baner',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMSVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'cms_video',
                'abstract': False,
            },
        ),
    ]
