# Generated by Django 3.0.5 on 2020-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsbanner',
            name='sort',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cmsvideo',
            name='sort',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cmsbanner',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='images/banner/'),
        ),
    ]
