# Generated by Django 3.0.5 on 2020-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200428_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsbanner',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='images/banner'),
        ),
    ]
