# Generated by Django 3.0.4 on 2020-03-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='d:\\PROGRAMS\\DJANGO3\\pluto\\media/images/user'),
        ),
    ]
