# Generated by Django 3.0.4 on 2020-03-20 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_expired', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Lunas'), ('pending', 'Belum dibayar')], default='pending', max_length=255)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.BigIntegerField()),
                ('response_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('response_guide', models.CharField(blank=True, max_length=500, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topup',
                'verbose_name_plural': 'Topups',
                'db_table': 'person_topup',
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
