# Generated by Django 3.0.4 on 2020-03-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200320_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='amount',
            new_name='payment_amount',
        ),
        migrations.RenameField(
            model_name='topup',
            old_name='response_guide',
            new_name='payment_guide',
        ),
        migrations.RenameField(
            model_name='topup',
            old_name='response_message',
            new_name='payment_message',
        ),
        migrations.RenameField(
            model_name='topup',
            old_name='order_id',
            new_name='payment_order_id',
        ),
        migrations.RenameField(
            model_name='topup',
            old_name='channel',
            new_name='payment_status_code',
        ),
        migrations.RenameField(
            model_name='topup',
            old_name='response_status',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='status',
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_status',
            field=models.CharField(choices=[('capture', 'Capture'), ('pending', 'Pending'), ('settlement', 'Settlement'), ('cancel', 'Cancel'), ('expired', 'Expired')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='topup',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_used': False, 'status': 'settlement'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='payment.TopUp'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar')], default='in', max_length=255),
        ),
    ]
