# Generated by Django 3.0.4 on 2020-03-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200321_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='date_expired',
            new_name='payment_created_date',
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
