# Generated by Django 3.0.4 on 2020-03-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200321_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='current_amount',
        ),
    ]
