# Generated by Django 3.0.4 on 2020-03-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_coin_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='payment_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='topup',
            field=models.ForeignKey(blank=True, limit_choices_to={'payment_status': 'settlement'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='payment.TopUp'),
        ),
    ]
