# Generated by Django 3.0.4 on 2020-03-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200321_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
