# Generated by Django 3.0.4 on 2020-03-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0009_coin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'payment'), ('model', 'topup')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='coin',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
