# Generated by Django 3.0.4 on 2020-03-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0010_auto_20200329_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='topup',
        ),
        migrations.AlterField(
            model_name='coin',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'payment'), ('model', 'topup')), models.Q(('app_label', 'mypoints'), ('model', 'points')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
