# Generated by Django 3.0.4 on 2020-03-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200329_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='content_type',
            new_name='caused_content_type',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='object_id',
            new_name='caused_object_id',
        ),
    ]
