# Generated by Django 3.0.4 on 2020-03-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0013_auto_20200330_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='caused_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'payment'), ('model', 'topup')), models.Q(('app_label', 'mypoints'), ('model', 'points')), models.Q(('app_label', 'market'), ('model', 'voucherredeem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
